insert into T_MS_PHYEXA
  (ID,
   NAME,
   TEST_DATE,
   TESTER_NAME,
   TESTING_ORG_NAME,
   CREATETIME,
   
   UPLOAD_ORG_CODE,
   OTHER_SYMPTOM_DESCR,
   BODY_TEMPERATURE,
   PULSE_RATE,
   BREATHE_FREQ,
   -- LEFT_SBP,
   --LEFT_DBP,
   RIGHT_SBP,
   RIGHT_DBP,
   
   BODY_HEIGHT,
   BODY_WEIGHT,
   WAIST_LINE,
   BODY_WEIGHT_INDEX,
   HIP_CIRCUM,
   RATIO,
   OLD_HEALTH_DN,
   OLD_ASSESS_DN,
   OLDER_COGNIZE_RESULT_VALUE,
   OLDER_EM_STATUS_RE_VALUE,
   EXERCISE_FREQ_DN,
   EXERCISE_TS,
   EXERCISE_MONTH,
   EXERCISE_DESCR,
   --饮食习惯（子表）
   SMOKING_STATUS_VALUE,
   DRINK_FREQ_DN,
   OE_VALUE,
   LIPS_DN,
   --齿列（子表）
   PHARYNX_VALUE,
   LEFT_FSM,
   RIGHT_FSM,
   AUDI_VALUE,
   ACTING_FUNCTION_VALUE,
   EYEGROUND_VALUE,
   OTHER_SKIN_DESCR,
   SCLERA_TEST_RESTULT_DN,
   LN_TEST_RESULT_DN,
   BARREL_CHEST_VALUE,
   LUNG_ABC_DESCR,
   LUNG_RALE_VALUE,
   HEART_RATE,
   ROH_VALUE,
   CS_VALUE,
   ABDOMINAL_TENDERNESS_VALUE,
   ABDOMINAL_MASS_VALUE,
   HEPATAUXE_VALUE,
   SPLENAUX_VALUE,
   ABDOMINAL_SONANT_VALUE,
   EOLE_TEST_RESULT_DN,
   INSTEP_ATPM_DN,
   FBS_MG_VALUE,
   U_PRO_TEST_RESULT_DN,
   GLU_TEST_RESULT_DN,
   UK_QUALITY_TEST_RESULT_DN,
   UOB_TEST_RESULT_DN,
   U_OTHERS,
   SOB_VALUE,
   SGPT_VALUE,
   SGOT_VALUE,
   TBIL_VALUE,
   SERUM_CR_TEST_VALUE,
   BUN_TEST_VALUE,
   T_CHO_VALUE,
   TG_VALUE,
   LDL_C_TEST_VALUE,
   HDL_C_TEST_VALUE,
   HBSAG_TEST_RESULT_VALUE,
   ECG_ABNORMAL_VALUE,
   ECG_ABNORMAL_DESCR,
   CXR_TEST_VALUE,
   ULT_ABNORMAL_VALUE,
   ON_DESCR,
   OSZ_DESCR,
   OXZ_DESCR,
   OXG_DESCR,
   OYB_DESCR,
   MENTAL_DIS_DESCR,
   OTHER_DIS_VALUE,
   HEALTH_EVA_ABNORMAL_VALUE,
   --健康评价-异常1（子表T_MS_PHYEXA_ASSESS）
   --健康评价-异常2
   --健康评价-异常3
   --健康评价-异常4
   --健康评价-异常5
   --健康指导（T_MS_PHYEXA_GUIDE）
   --危险因素控制（T_MS_PHYEXA_RISCONT）
   
   FIELD_PK_FK,
   FIELD_PK
   
   )
values
  (
  'UUID-id',   -- ID,
   '杨秀兰',   -- NAME,
   to_date('2012-10-31', 'yyyy-mm-dd'),   -- TEST_DATE,
   '彭博',   -- TESTER_NAME,
   '永乐店社区服务中心',   -- TESTING_ORG_NAME,
   to_date('2012-08-28', 'yyyy-mm-dd'),   -- CREATETIME,
   'yuxin',   -- UPLOAD_ORG_CODE,
   '无症状',   -- OTHER_SYMPTOM_DESCR,
   37,   -- BODY_TEMPERATURE,
   75,   -- PULSE_RATE,
   18,   -- BREATHE_FREQ,
   173,   -- RIGHT_SBP,
   120,   -- RIGHT_DBP,
   155,   -- BODY_HEIGHT,
   58,   -- BODY_WEIGHT,
   78,   -- WAIST_LINE,
   24,   -- BODY_WEIGHT_INDEX,
   92,   -- HIP_CIRCUM,
   0.84,   -- RATIO,
   '满意',   -- OLD_HEALTH_DN,
   '可自理',   -- OLD_ASSESS_DN,
   '粗筛阴性',   -- OLDER_COGNIZE_RESULT_VALUE,
   '粗筛阴性',   -- OLDER_EM_STATUS_RE_VALUE,
   '每天',   -- EXERCISE_FREQ_DN,
   30,   -- EXERCISE_TS,
   10,   -- EXERCISE_MONTH,
   '散步',   -- EXERCISE_DESCR,
   '从不吸烟',   -- SMOKING_STATUS_VALUE,
   '从不',   -- DRINK_FREQ_DN,
   '无',   -- OE_VALUE,
   '红润',   -- LIPS_DN,
   '无充血',   -- PHARYNX_VALUE,
   4.7,   -- LEFT_FSM,
   4.8,   -- RIGHT_FSM,
   '听见',   -- AUDI_VALUE,
   '可顺利完成',   -- ACTING_FUNCTION_VALUE,
   '正常',   -- EYEGROUND_VALUE,
   '正常',   -- OTHER_SKIN_DESCR,
   '正常',   -- SCLERA_TEST_RESTULT_DN,
   '未触及',   -- LN_TEST_RESULT_DN,
   '否',   -- BARREL_CHEST_VALUE,
   '正常',   -- LUNG_ABC_DESCR,
   '无',   -- LUNG_RALE_VALUE,
   75,   -- HEART_RATE,
   '齐',   -- ROH_VALUE,
   '无',   -- CS_VALUE,
   '无',   -- ABDOMINAL_TENDERNESS_VALUE,
   '无',   -- ABDOMINAL_MASS_VALUE,
   '无',   -- HEPATAUXE_VALUE,
   '无',   -- SPLENAUX_VALUE,
   '无',   -- ABDOMINAL_SONANT_VALUE,
   '无',   -- EOLE_TEST_RESULT_DN,
   '触及双侧对称',   -- INSTEP_ATPM_DN,
   5.3,   -- FBS_MG_VALUE,
   '+',   -- U_PRO_TEST_RESULT_DN,
   '-',   -- GLU_TEST_RESULT_DN,
   '-',   -- UK_QUALITY_TEST_RESULT_DN,
   '-',   -- UOB_TEST_RESULT_DN,
   '白细胞2+',   -- U_OTHERS,
   '阴性',   -- SOB_VALUE,
   22,   -- SGPT_VALUE,
   16,   -- SGOT_VALUE,
   17.3,   -- TBIL_VALUE,
   105,   -- SERUM_CR_TEST_VALUE,
   5.6,   -- BUN_TEST_VALUE,
   5.3,   -- T_CHO_VALUE,
   1.6,   -- TG_VALUE,
   3.1,   -- LDL_C_TEST_VALUE,
   1.5,   -- HDL_C_TEST_VALUE,
   '阴性',   -- HBSAG_TEST_RESULT_VALUE,
   '异常',   -- ECG_ABNORMAL_VALUE,
   'st-t改变',   -- ECG_ABNORMAL_DESCR,
   '正常',   -- CXR_TEST_VALUE,
   '正常',   -- ULT_ABNORMAL_VALUE,
   '未发现',   -- ON_DESCR,
   '未发现',   -- OSZ_DESCR,
   '未发现',   -- OXZ_DESCR,
   '未发现',   -- OXG_DESCR,
   '未发现',   -- OYB_DESCR,
   '未发现',   -- MENTAL_DIS_DESCR,
   '未发现',   -- OTHER_DIS_VALUE,
   '有异常',   -- HEALTH_EVA_ABNORMAL_VALUE,
   'UUID-pk-fk',   -- FIELD_PK_FK,
   'UUID-pk' --FIELD_PK,
   );
