insert into T_MS_PHYEXA
  (
  TEST_DATE,
  TESTING_ORG_NAME,
  HEALTH_PROBLEM_DN,
  UPLOAD_ORG_CODE,
  ID,
  NAME,
  BODY_HEIGHT,
  BODY_WEIGHT,
  BODY_TEMPERATURE,
  PULSE_RATE,
  BREATHE_FREQ,
  LEFT_SBP,
  LEFT_DBP,
  --一般情况
  OTHER_SKIN_DESCR,
  OTHER_LN_DESCR,
  --结膜
  --角膜
  OTHER_SCLERA_DESCR,
  --瞳孔
  AUDI_VALUE,
  --鼻
  --舌
  PHARYNX_VALUE,
  --双侧扁桃体
  --支气管
  --颈静脉
  --颈动脉搏动
  OXG_DESCR,
  --甲状腺
  --胸廓
  OTHER_BREAST_DESCR,
  LUNG_ABC_DESCR,
  OXZ_DESCR,
  DRE_RESULT_DN,
  --脊柱
  --生理反射
  --病理反射
  --脑膜刺激征
  CNDRUG_CON_RESULT_VALUE, 
  CREATETIME,
  OTHER_EXAMINATION_RESULT,
  TESTER_NAME,
  --2012-09-17
  
  FIELD_PK_FK,
  FIELD_PK
  
  
  )
  values
  (
  to_date('2012-09-17','yyyy-mm-dd'),
  '永乐店社区服务中心',
  '体检发现血糖升高6年',
  'yuxin',
  'pk-uuid',
  '杨秀兰',
  '155',
  '58',
  '37',
  '70',
  '18',
  '173',
  '120',
  '未见黄染、皮疹、出血点',
  '全身浅表淋巴结无肿大',
  '无染黄',
  '听力正常，无流脓，乳突无压痛',
  '无充血',
  '未闻及',
  '对称，未及肿块',
  '双侧呼吸运动对称，双肺呼吸音清，未闻及干湿罗音',
  '心前区无隆起，心尖部无震颤，无摩擦感及抬举性心尖搏动，心率     次/分，律齐，各瓣膜听诊区未闻及病理性杂音',
  '未查',
  '平和质、阴虚质、阳虚质、气虚质、痰湿质、湿热质、血淤质、气郁质、特禀质等',
  to_date('2012-09-17','yyyy-mm-dd'),
  '2型糖尿病',
  '薛楠',
  '1ae675c0-329a-4cb5-bddf-dbb40cccf68a',
  'UUID-pk-fk'
  );