insert into T_MS_PHYEXA
  (
  TEST_DATE,
  TESTING_ORG_NAME,
  HEALTH_PROBLEM_DN,
  UPLOAD_ORG_CODE,
  ID,
  NAME,
  BODY_HEIGHT,
  BODY_WEIGHT,
  BODY_TEMPERATURE,
  PULSE_RATE,
  BREATHE_FREQ,
  LEFT_SBP,
  LEFT_DBP,
  --一般情况
  OTHER_SKIN_DESCR,
  OTHER_LN_DESCR,
  --结膜
  --角膜
  OTHER_SCLERA_DESCR,
  --瞳孔
  AUDI_VALUE,
  --鼻
  --舌
  PHARYNX_VALUE,
  --双侧扁桃体
  --支气管
  --颈静脉
  --颈动脉搏动
  OXG_DESCR,
  --甲状腺
  --胸廓
  OTHER_BREAST_DESCR,
  LUNG_ABC_DESCR,
  OXZ_DESCR,
  DRE_RESULT_DN,
  --脊柱
  --生理反射
  --病理反射
  --脑膜刺激征
  CNDRUG_CON_RESULT_VALUE, 
  CREATETIME,
  OTHER_EXAMINATION_RESULT,
  TESTER_NAME,
  --2012-09-17
  
  FIELD_PK_FK,
  FIELD_PK
  
  
  )
  values
  (
  to_date('${TEST_DATE}','yyyy-mm-dd'),
  '${TESTING_ORG_NAME}',
  '${HEALTH_PROBLEM_DN}',
  '${UPLOAD_ORG_CODE}',
  '${ID}',
  '${NAME}',
  '${BODY_HEIGHT}',
  '${BODY_WEIGHT}',
  '${BODY_TEMPERATURE}',
  '${PULSE_RATE}',
  '${BREATHE_FREQ}',
  '${LEFT_SBP}',
  '${LEFT_DBP}',
  '${OTHER_SKIN_DESCR}',
  '${OTHER_LN_DESCR}',
  '${OTHER_SCLERA_DESCR}',
  '${AUDI_VALUE}',
  '${PHARYNX_VALUE}',
  '${OXG_DESCR}',
  '${OTHER_BREAST_DESCR}',
  '${LUNG_ABC_DESCR}',
  '${OXZ_DESCR}',
  '${DRE_RESULT_DN}',
  '${CNDRUG_CON_RESULT_VALUE}', 
  to_date('${CREATETIME}','yyyy-mm-dd'),
  '${OTHER_EXAMINATION_RESULT}',
  '${TESTER_NAME}',
  '${FIELD_PK_FK}',
  '${FIELD_PK}'
);